name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: random_number
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          random_number

    - name: Install erlkaf dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsasl2-dev liblz4-dev libzstd-dev libcurl3-dev

    - uses: erlef/setup-beam@v1
      id: setup-beam
      with:
        elixir-version: 1.16.3
        otp-version: 25.3.2.12

    - name: Restore Dependency Cache
      uses: actions/cache@v4
      id: cache-deps
      with:
        path: | 
          random_number/deps
          random_number/_build
        key: ${{ runner.os }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ steps.setup-beam.outputs.otp-version }}-${{ hashFiles('random_number/mix.lock') }}

    - run: mix deps.get
      if: steps.cache-deps.outputs.cache-hit != 'true'
    - run: mix deps.compile --warnings-as-errors
      if: steps.cache-deps.outputs.cache-hit != 'true'
    - run: mix deps.unlock --unused
      if: steps.cache-deps.outputs.cache-hit != 'true'

    - run: mix format --check-formatted

    - name: Check for abondoned dependencies
      run: mix hex.audit

    - run: mix test
